### ISSUE TITLE
use outside of remote dev?

### ISSUE THREAD

**Issue by rt2zz** [zalmoxisus/remotedev-serialize#4]
We are strongly considering using this in redux-persist-tranform-immutable (re: https://github.com/rt2zz/redux-persist-transform-immutable/pull/25) as it is much smaller than transit and works with immutable 4. Wondering if you have any hesitations here? Especially looking at the name it seems this module may have really been intended solely for use with remote devtools.

**Comment by zalmoxisus** [comment]
Hey @rt2zz! Sorry for replaying after more than an year :-(
Of course you can use it and include it in your libraries. Originally it was named `serialize-immutable`, but then we thought (there's a discussion in extension repo), that we could make it more generic so it could be used for serializing other similar data.
